const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let role='aluno',name='';
const menus={aluno:[['inicio','Início'],['notas','Notas'],['frequencia','Frequência'],['atividades','Atividades'],['calendario','Calendário'],['avisos','Avisos']],professor:[['inicio','Início'],['turmas','Minhas turmas'],['notas','Lançar notas'],['atividades','Atividades'],['avisos','Avisos']]};
$$('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;$('#loginTitle').textContent=role==='aluno'?'Área do Aluno':'Área do Professor';$('#icon').textContent=role==='aluno'?'🎓':'📚';$('#login').classList.add('show');$('#name').focus()});
$('#close').onclick=()=>$('#login').classList.remove('show');
$('#login').onclick=e=>{if(e.target.id==='login')$('#login').classList.remove('show')};
$('#loginForm').onsubmit=e=>{e.preventDefault();name=$('#name').value.trim();$('#login').classList.remove('show');$('#portal').classList.add('show');$('#user').innerHTML='Olá, <b>'+esc(name)+'</b>';$('#role').textContent=role==='aluno'?'Portal do Aluno':'Portal do Professor';build();render('inicio')};
function build(){let n=$('#pnav');n.innerHTML=menus[role].map(x=>'<button data-page="'+x[0]+'">'+x[1]+'</button>').join('');$$('[data-page]').forEach(b=>b.onclick=()=>{render(b.dataset.page);$('.portal aside').classList.remove('open')})}
function render(page){$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));let labels=Object.fromEntries(menus[role]);$('#title').textContent=labels[page]||'Início';let h='';
if(role==='aluno'){if(page==='inicio')h='<div class="dash"><div class="box"><p>Boletim</p><strong>8,7</strong><p>Média geral</p></div><div class="box"><p>Frequência</p><strong>96%</strong><p>Presença</p></div><div class="box"><p>Atividades</p><strong>4</strong><p>Pendentes</p></div></div><div class="notice"><b>Bem-vindo ao Portal do Aluno!</b><br>Acompanhe suas informações escolares pelo menu.</div>';
if(page==='notas')h='<table class="ptable"><tr><th>Disciplina</th><th>1º Bim.</th><th>2º Bim.</th><th>Média</th></tr>'+['Português','Matemática','Ciências','História','Geografia','Inglês'].map((x,i)=>'<tr><td>'+x+'</td><td>'+[8.5,9,8,8.7,9,8.3][i]+'</td><td>'+[9,8.5,8.7,9,8.8,8.6][i]+'</td><td>'+[8.7,8.7,8.4,8.8,8.9,8.4][i]+'</td></tr>').join('')+'</table>';
if(page==='frequencia')h='<div class="dash"><div class="box"><p>Presença</p><strong>96%</strong></div><div class="box"><p>Faltas</p><strong>4</strong></div><div class="box"><p>Ano</p><strong>2026</strong></div></div><div class="notice">Sua frequência está sendo acompanhada pela escola.</div>';
if(page==='atividades')h=['Trabalho de Ciências','Lista de Matemática','Pesquisa de História'].map((x,i)=>'<div class="activity"><div><b>'+x+'</b><p>Atividade disponível para entrega.</p></div><span class="tag">'+(i?'Em andamento':'Entrega 20/09')+'</span></div>').join('');
if(page==='calendario')h='<div class="notice"><b>18/09</b> — Avaliação de Matemática</div><div class="notice"><b>24/09</b> — Entrega de trabalho</div><div class="notice"><b>30/09</b> — Reunião escolar</div>';
if(page==='avisos')h='<div class="notice"><b>Comunicado escolar</b><br>Confira os próximos eventos e atividades.</div><div class="notice"><b>Portal do aluno</b><br>Novas informações podem aparecer aqui.</div>';
}else{if(page==='inicio')h='<div class="dash"><div class="box"><p>Turmas</p><strong>4</strong><p>Ativas</p></div><div class="box"><p>Alunos</p><strong>96</strong><p>Acompanhados</p></div><div class="box"><p>Atividades</p><strong>7</strong><p>Publicadas</p></div></div><div class="notice"><b>Bem-vindo ao Portal do Professor!</b><br>Use o menu para acessar suas ferramentas.</div>';
if(page==='turmas')h='<div class="cards"><article><h3>9º ano</h3><p>24 alunos • Sala 01</p><button class="red" onclick="alert(\'Turma do 9º ano aberta — demonstração.\')">Abrir turma</button></article><article><h3>8º ano</h3><p>26 alunos • Sala 02</p><button class="red" onclick="alert(\'Turma do 8º ano aberta — demonstração.\')">Abrir turma</button></article><article><h3>7º ano</h3><p>23 alunos • Sala 03</p><button class="red" onclick="alert(\'Turma do 7º ano aberta — demonstração.\')">Abrir turma</button></article></div>';
if(page==='notas')h='<div class="notice"><b>Lançamento de notas</b><br>Escolha uma turma.</div><div class="cards"><article><h3>9º ano</h3><p>24 alunos</p><button class="red" onclick="alert(\'Área de lançamento — demonstração.\')">Lançar notas</button></article><article><h3>8º ano</h3><p>26 alunos</p><button class="red" onclick="alert(\'Área de lançamento — demonstração.\')">Lançar notas</button></article></div>';
if(page==='atividades')h='<button class="red" onclick="alert(\'Nova atividade — demonstração.\')">+ Nova atividade</button><br><br><div class="activity"><div><b>Trabalho de Ciências</b><p>Publicado para o 9º ano.</p></div><span class="tag">Publicado</span></div><div class="activity"><div><b>Lista de Matemática</b><p>Publicado para o 8º ano.</p></div><span class="tag">Publicado</span></div>';
if(page==='avisos')h='<button class="red" onclick="alert(\'Novo aviso — demonstração.\')">+ Novo aviso</button><br><br><div class="notice"><b>Reunião pedagógica</b><br>Comunicado para os professores.</div><div class="notice"><b>Calendário</b><br>Confira as próximas datas escolares.</div>'}
$('#content').innerHTML='<div class="pcontent">'+h+'</div>'}
$('#logout').onclick=()=>{$('#portal').classList.remove('show');$('#loginForm').reset()};
$('#pmenu').onclick=()=>$('.portal aside').classList.toggle('open');
$('#menu').onclick=()=>$('#links').classList.toggle('open');
$('#form').onsubmit=e=>{e.preventDefault();alert('Obrigado! O interesse em matrícula foi enviado.');e.target.reset()};
function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
